from afs.exceptions.AfsError import AfsError


class CMError(AfsError):
    pass

    
