from afs.exceptions.AfsError import AfsError

class krb5Error(AfsError):
    pass
