from afs.exceptions.AfsError import AfsError

class VLDbError(AfsError):
    pass
